[project]
name = 'Blockchain-Based-Urban-Floating-City-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.city-verification]
path = 'contracts/city-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.environmental-integration]
path = 'contracts/environmental-integration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
